using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Quantum
{
  public static class PolymerColor
  {
      public static readonly ColorRGBA paper_red_50 = new ColorRGBA("ffebee");
      public static readonly ColorRGBA paper_red_100 = new ColorRGBA("ffcdd2");
      public static readonly ColorRGBA paper_red_200 = new ColorRGBA("ef9a9a");
      public static readonly ColorRGBA paper_red_300 = new ColorRGBA("e57373");
      public static readonly ColorRGBA paper_red_400 = new ColorRGBA("ef5350");
      public static readonly ColorRGBA paper_red_500 = new ColorRGBA("f44336");
      public static readonly ColorRGBA paper_red_600 = new ColorRGBA("e53935");
      public static readonly ColorRGBA paper_red_700 = new ColorRGBA("d32f2f");
      public static readonly ColorRGBA paper_red_800 = new ColorRGBA("c62828");
      public static readonly ColorRGBA paper_red_900 = new ColorRGBA("b71c1c");
      public static readonly ColorRGBA paper_red_a100 = new ColorRGBA("ff8a80");
      public static readonly ColorRGBA paper_red_a200 = new ColorRGBA("ff5252");
      public static readonly ColorRGBA paper_red_a400 = new ColorRGBA("ff1744");
      public static readonly ColorRGBA paper_red_a700 = new ColorRGBA("d50000");

      public static readonly ColorRGBA paper_pink_50 = new ColorRGBA("fce4ec");
      public static readonly ColorRGBA paper_pink_100 = new ColorRGBA("f8bbd0");
      public static readonly ColorRGBA paper_pink_200 = new ColorRGBA("f48fb1");
      public static readonly ColorRGBA paper_pink_300 = new ColorRGBA("f06292");
      public static readonly ColorRGBA paper_pink_400 = new ColorRGBA("ec407a");
      public static readonly ColorRGBA paper_pink_500 = new ColorRGBA("e91e63");
      public static readonly ColorRGBA paper_pink_600 = new ColorRGBA("d81b60");
      public static readonly ColorRGBA paper_pink_700 = new ColorRGBA("c2185b");
      public static readonly ColorRGBA paper_pink_800 = new ColorRGBA("ad1457");
      public static readonly ColorRGBA paper_pink_900 = new ColorRGBA("880e4f");
      public static readonly ColorRGBA paper_pink_a100 = new ColorRGBA("ff80ab");
      public static readonly ColorRGBA paper_pink_a200 = new ColorRGBA("ff4081");
      public static readonly ColorRGBA paper_pink_a400 = new ColorRGBA("f50057");
      public static readonly ColorRGBA paper_pink_a700 = new ColorRGBA("c51162");

      public static readonly ColorRGBA paper_purple_50 = new ColorRGBA("f3e5f5");
      public static readonly ColorRGBA paper_purple_100 = new ColorRGBA("e1bee7");
      public static readonly ColorRGBA paper_purple_200 = new ColorRGBA("ce93d8");
      public static readonly ColorRGBA paper_purple_300 = new ColorRGBA("ba68c8");
      public static readonly ColorRGBA paper_purple_400 = new ColorRGBA("ab47bc");
      public static readonly ColorRGBA paper_purple_500 = new ColorRGBA("9c27b0");
      public static readonly ColorRGBA paper_purple_600 = new ColorRGBA("8e24aa");
      public static readonly ColorRGBA paper_purple_700 = new ColorRGBA("7b1fa2");
      public static readonly ColorRGBA paper_purple_800 = new ColorRGBA("6a1b9a");
      public static readonly ColorRGBA paper_purple_900 = new ColorRGBA("4a148c");
      public static readonly ColorRGBA paper_purple_a100 = new ColorRGBA("ea80fc");
      public static readonly ColorRGBA paper_purple_a200 = new ColorRGBA("e040fb");
      public static readonly ColorRGBA paper_purple_a400 = new ColorRGBA("d500f9");
      public static readonly ColorRGBA paper_purple_a700 = new ColorRGBA("aa00ff");

      public static readonly ColorRGBA paper_deep_purple_50 = new ColorRGBA("ede7f6");
      public static readonly ColorRGBA paper_deep_purple_100 = new ColorRGBA("d1c4e9");
      public static readonly ColorRGBA paper_deep_purple_200 = new ColorRGBA("b39ddb");
      public static readonly ColorRGBA paper_deep_purple_300 = new ColorRGBA("9575cd");
      public static readonly ColorRGBA paper_deep_purple_400 = new ColorRGBA("7e57c2");
      public static readonly ColorRGBA paper_deep_purple_500 = new ColorRGBA("673ab7");
      public static readonly ColorRGBA paper_deep_purple_600 = new ColorRGBA("5e35b1");
      public static readonly ColorRGBA paper_deep_purple_700 = new ColorRGBA("512da8");
      public static readonly ColorRGBA paper_deep_purple_800 = new ColorRGBA("4527a0");
      public static readonly ColorRGBA paper_deep_purple_900 = new ColorRGBA("311b92");
      public static readonly ColorRGBA paper_deep_purple_a100 = new ColorRGBA("b388ff");
      public static readonly ColorRGBA paper_deep_purple_a200 = new ColorRGBA("7c4dff");
      public static readonly ColorRGBA paper_deep_purple_a400 = new ColorRGBA("651fff");
      public static readonly ColorRGBA paper_deep_purple_a700 = new ColorRGBA("6200ea");

      public static readonly ColorRGBA paper_indigo_50 = new ColorRGBA("e8eaf6");
      public static readonly ColorRGBA paper_indigo_100 = new ColorRGBA("c5cae9");
      public static readonly ColorRGBA paper_indigo_200 = new ColorRGBA("9fa8da");
      public static readonly ColorRGBA paper_indigo_300 = new ColorRGBA("7986cb");
      public static readonly ColorRGBA paper_indigo_400 = new ColorRGBA("5c6bc0");
      public static readonly ColorRGBA paper_indigo_500 = new ColorRGBA("3f51b5");
      public static readonly ColorRGBA paper_indigo_600 = new ColorRGBA("3949ab");
      public static readonly ColorRGBA paper_indigo_700 = new ColorRGBA("303f9f");
      public static readonly ColorRGBA paper_indigo_800 = new ColorRGBA("283593");
      public static readonly ColorRGBA paper_indigo_900 = new ColorRGBA("1a237e");
      public static readonly ColorRGBA paper_indigo_a100 = new ColorRGBA("8c9eff");
      public static readonly ColorRGBA paper_indigo_a200 = new ColorRGBA("536dfe");
      public static readonly ColorRGBA paper_indigo_a400 = new ColorRGBA("3d5afe");
      public static readonly ColorRGBA paper_indigo_a700 = new ColorRGBA("304ffe");

      public static readonly ColorRGBA paper_blue_50 = new ColorRGBA("e3f2fd");
      public static readonly ColorRGBA paper_blue_100 = new ColorRGBA("bbdefb");
      public static readonly ColorRGBA paper_blue_200 = new ColorRGBA("90caf9");
      public static readonly ColorRGBA paper_blue_300 = new ColorRGBA("64b5f6");
      public static readonly ColorRGBA paper_blue_400 = new ColorRGBA("42a5f5");
      public static readonly ColorRGBA paper_blue_500 = new ColorRGBA("2196f3");
      public static readonly ColorRGBA paper_blue_600 = new ColorRGBA("1e88e5");
      public static readonly ColorRGBA paper_blue_700 = new ColorRGBA("1976d2");
      public static readonly ColorRGBA paper_blue_800 = new ColorRGBA("1565c0");
      public static readonly ColorRGBA paper_blue_900 = new ColorRGBA("0d47a1");
      public static readonly ColorRGBA paper_blue_a100 = new ColorRGBA("82b1ff");
      public static readonly ColorRGBA paper_blue_a200 = new ColorRGBA("448aff");
      public static readonly ColorRGBA paper_blue_a400 = new ColorRGBA("2979ff");
      public static readonly ColorRGBA paper_blue_a700 = new ColorRGBA("2962ff");

      public static readonly ColorRGBA paper_light_blue_50 = new ColorRGBA("e1f5fe");
      public static readonly ColorRGBA paper_light_blue_100 = new ColorRGBA("b3e5fc");
      public static readonly ColorRGBA paper_light_blue_200 = new ColorRGBA("81d4fa");
      public static readonly ColorRGBA paper_light_blue_300 = new ColorRGBA("4fc3f7");
      public static readonly ColorRGBA paper_light_blue_400 = new ColorRGBA("29b6f6");
      public static readonly ColorRGBA paper_light_blue_500 = new ColorRGBA("03a9f4");
      public static readonly ColorRGBA paper_light_blue_600 = new ColorRGBA("039be5");
      public static readonly ColorRGBA paper_light_blue_700 = new ColorRGBA("0288d1");
      public static readonly ColorRGBA paper_light_blue_800 = new ColorRGBA("0277bd");
      public static readonly ColorRGBA paper_light_blue_900 = new ColorRGBA("01579b");
      public static readonly ColorRGBA paper_light_blue_a100 = new ColorRGBA("80d8ff");
      public static readonly ColorRGBA paper_light_blue_a200 = new ColorRGBA("40c4ff");
      public static readonly ColorRGBA paper_light_blue_a400 = new ColorRGBA("00b0ff");
      public static readonly ColorRGBA paper_light_blue_a700 = new ColorRGBA("0091ea");

      public static readonly ColorRGBA paper_cyan_50 = new ColorRGBA("e0f7fa");
      public static readonly ColorRGBA paper_cyan_100 = new ColorRGBA("b2ebf2");
      public static readonly ColorRGBA paper_cyan_200 = new ColorRGBA("80deea");
      public static readonly ColorRGBA paper_cyan_300 = new ColorRGBA("4dd0e1");
      public static readonly ColorRGBA paper_cyan_400 = new ColorRGBA("26c6da");
      public static readonly ColorRGBA paper_cyan_500 = new ColorRGBA("00bcd4");
      public static readonly ColorRGBA paper_cyan_600 = new ColorRGBA("00acc1");
      public static readonly ColorRGBA paper_cyan_700 = new ColorRGBA("0097a7");
      public static readonly ColorRGBA paper_cyan_800 = new ColorRGBA("00838f");
      public static readonly ColorRGBA paper_cyan_900 = new ColorRGBA("006064");
      public static readonly ColorRGBA paper_cyan_a100 = new ColorRGBA("84ffff");
      public static readonly ColorRGBA paper_cyan_a200 = new ColorRGBA("18ffff");
      public static readonly ColorRGBA paper_cyan_a400 = new ColorRGBA("00e5ff");
      public static readonly ColorRGBA paper_cyan_a700 = new ColorRGBA("00b8d4");

      public static readonly ColorRGBA paper_teal_50 = new ColorRGBA("e0f2f1");
      public static readonly ColorRGBA paper_teal_100 = new ColorRGBA("b2dfdb");
      public static readonly ColorRGBA paper_teal_200 = new ColorRGBA("80cbc4");
      public static readonly ColorRGBA paper_teal_300 = new ColorRGBA("4db6ac");
      public static readonly ColorRGBA paper_teal_400 = new ColorRGBA("26a69a");
      public static readonly ColorRGBA paper_teal_500 = new ColorRGBA("009688");
      public static readonly ColorRGBA paper_teal_600 = new ColorRGBA("00897b");
      public static readonly ColorRGBA paper_teal_700 = new ColorRGBA("00796b");
      public static readonly ColorRGBA paper_teal_800 = new ColorRGBA("00695c");
      public static readonly ColorRGBA paper_teal_900 = new ColorRGBA("004d40");
      public static readonly ColorRGBA paper_teal_a100 = new ColorRGBA("a7ffeb");
      public static readonly ColorRGBA paper_teal_a200 = new ColorRGBA("64ffda");
      public static readonly ColorRGBA paper_teal_a400 = new ColorRGBA("1de9b6");
      public static readonly ColorRGBA paper_teal_a700 = new ColorRGBA("00bfa5");

      public static readonly ColorRGBA paper_green_50 = new ColorRGBA("e8f5e9");
      public static readonly ColorRGBA paper_green_100 = new ColorRGBA("c8e6c9");
      public static readonly ColorRGBA paper_green_200 = new ColorRGBA("a5d6a7");
      public static readonly ColorRGBA paper_green_300 = new ColorRGBA("81c784");
      public static readonly ColorRGBA paper_green_400 = new ColorRGBA("66bb6a");
      public static readonly ColorRGBA paper_green_500 = new ColorRGBA("4caf50");
      public static readonly ColorRGBA paper_green_600 = new ColorRGBA("43a047");
      public static readonly ColorRGBA paper_green_700 = new ColorRGBA("388e3c");
      public static readonly ColorRGBA paper_green_800 = new ColorRGBA("2e7d32");
      public static readonly ColorRGBA paper_green_900 = new ColorRGBA("1b5e20");
      public static readonly ColorRGBA paper_green_a100 = new ColorRGBA("b9f6ca");
      public static readonly ColorRGBA paper_green_a200 = new ColorRGBA("69f0ae");
      public static readonly ColorRGBA paper_green_a400 = new ColorRGBA("00e676");
      public static readonly ColorRGBA paper_green_a700 = new ColorRGBA("00c853");

      public static readonly ColorRGBA paper_light_green_50 = new ColorRGBA("f1f8e9");
      public static readonly ColorRGBA paper_light_green_100 = new ColorRGBA("dcedc8");
      public static readonly ColorRGBA paper_light_green_200 = new ColorRGBA("c5e1a5");
      public static readonly ColorRGBA paper_light_green_300 = new ColorRGBA("aed581");
      public static readonly ColorRGBA paper_light_green_400 = new ColorRGBA("9ccc65");
      public static readonly ColorRGBA paper_light_green_500 = new ColorRGBA("8bc34a");
      public static readonly ColorRGBA paper_light_green_600 = new ColorRGBA("7cb342");
      public static readonly ColorRGBA paper_light_green_700 = new ColorRGBA("689f38");
      public static readonly ColorRGBA paper_light_green_800 = new ColorRGBA("558b2f");
      public static readonly ColorRGBA paper_light_green_900 = new ColorRGBA("33691e");
      public static readonly ColorRGBA paper_light_green_a100 = new ColorRGBA("ccff90");
      public static readonly ColorRGBA paper_light_green_a200 = new ColorRGBA("b2ff59");
      public static readonly ColorRGBA paper_light_green_a400 = new ColorRGBA("76ff03");
      public static readonly ColorRGBA paper_light_green_a700 = new ColorRGBA("64dd17");

      public static readonly ColorRGBA paper_lime_50 = new ColorRGBA("f9fbe7");
      public static readonly ColorRGBA paper_lime_100 = new ColorRGBA("f0f4c3");
      public static readonly ColorRGBA paper_lime_200 = new ColorRGBA("e6ee9c");
      public static readonly ColorRGBA paper_lime_300 = new ColorRGBA("dce775");
      public static readonly ColorRGBA paper_lime_400 = new ColorRGBA("d4e157");
      public static readonly ColorRGBA paper_lime_500 = new ColorRGBA("cddc39");
      public static readonly ColorRGBA paper_lime_600 = new ColorRGBA("c0ca33");
      public static readonly ColorRGBA paper_lime_700 = new ColorRGBA("afb42b");
      public static readonly ColorRGBA paper_lime_800 = new ColorRGBA("9e9d24");
      public static readonly ColorRGBA paper_lime_900 = new ColorRGBA("827717");
      public static readonly ColorRGBA paper_lime_a100 = new ColorRGBA("f4ff81");
      public static readonly ColorRGBA paper_lime_a200 = new ColorRGBA("eeff41");
      public static readonly ColorRGBA paper_lime_a400 = new ColorRGBA("c6ff00");
      public static readonly ColorRGBA paper_lime_a700 = new ColorRGBA("aeea00");

      public static readonly ColorRGBA paper_yellow_50 = new ColorRGBA("fffde7");
      public static readonly ColorRGBA paper_yellow_100 = new ColorRGBA("fff9c4");
      public static readonly ColorRGBA paper_yellow_200 = new ColorRGBA("fff59d");
      public static readonly ColorRGBA paper_yellow_300 = new ColorRGBA("fff176");
      public static readonly ColorRGBA paper_yellow_400 = new ColorRGBA("ffee58");
      public static readonly ColorRGBA paper_yellow_500 = new ColorRGBA("ffeb3b");
      public static readonly ColorRGBA paper_yellow_600 = new ColorRGBA("fdd835");
      public static readonly ColorRGBA paper_yellow_700 = new ColorRGBA("fbc02d");
      public static readonly ColorRGBA paper_yellow_800 = new ColorRGBA("f9a825");
      public static readonly ColorRGBA paper_yellow_900 = new ColorRGBA("f57f17");
      public static readonly ColorRGBA paper_yellow_a100 = new ColorRGBA("ffff8d");
      public static readonly ColorRGBA paper_yellow_a200 = new ColorRGBA("ffff00");
      public static readonly ColorRGBA paper_yellow_a400 = new ColorRGBA("ffea00");
      public static readonly ColorRGBA paper_yellow_a700 = new ColorRGBA("ffd600");

      public static readonly ColorRGBA paper_amber_50 = new ColorRGBA("fff8e1");
      public static readonly ColorRGBA paper_amber_100 = new ColorRGBA("ffecb3");
      public static readonly ColorRGBA paper_amber_200 = new ColorRGBA("ffe082");
      public static readonly ColorRGBA paper_amber_300 = new ColorRGBA("ffd54f");
      public static readonly ColorRGBA paper_amber_400 = new ColorRGBA("ffca28");
      public static readonly ColorRGBA paper_amber_500 = new ColorRGBA("ffc107");
      public static readonly ColorRGBA paper_amber_600 = new ColorRGBA("ffb300");
      public static readonly ColorRGBA paper_amber_700 = new ColorRGBA("ffa000");
      public static readonly ColorRGBA paper_amber_800 = new ColorRGBA("ff8f00");
      public static readonly ColorRGBA paper_amber_900 = new ColorRGBA("ff6f00");
      public static readonly ColorRGBA paper_amber_a100 = new ColorRGBA("ffe57f");
      public static readonly ColorRGBA paper_amber_a200 = new ColorRGBA("ffd740");
      public static readonly ColorRGBA paper_amber_a400 = new ColorRGBA("ffc400");
      public static readonly ColorRGBA paper_amber_a700 = new ColorRGBA("ffab00");

      public static readonly ColorRGBA paper_orange_50 = new ColorRGBA("fff3e0");
      public static readonly ColorRGBA paper_orange_100 = new ColorRGBA("ffe0b2");
      public static readonly ColorRGBA paper_orange_200 = new ColorRGBA("ffcc80");
      public static readonly ColorRGBA paper_orange_300 = new ColorRGBA("ffb74d");
      public static readonly ColorRGBA paper_orange_400 = new ColorRGBA("ffa726");
      public static readonly ColorRGBA paper_orange_500 = new ColorRGBA("ff9800");
      public static readonly ColorRGBA paper_orange_600 = new ColorRGBA("fb8c00");
      public static readonly ColorRGBA paper_orange_700 = new ColorRGBA("f57c00");
      public static readonly ColorRGBA paper_orange_800 = new ColorRGBA("ef6c00");
      public static readonly ColorRGBA paper_orange_900 = new ColorRGBA("e65100");
      public static readonly ColorRGBA paper_orange_a100 = new ColorRGBA("ffd180");
      public static readonly ColorRGBA paper_orange_a200 = new ColorRGBA("ffab40");
      public static readonly ColorRGBA paper_orange_a400 = new ColorRGBA("ff9100");
      public static readonly ColorRGBA paper_orange_a700 = new ColorRGBA("ff6500");

      public static readonly ColorRGBA paper_deep_orange_50 = new ColorRGBA("fbe9e7");
      public static readonly ColorRGBA paper_deep_orange_100 = new ColorRGBA("ffccbc");
      public static readonly ColorRGBA paper_deep_orange_200 = new ColorRGBA("ffab91");
      public static readonly ColorRGBA paper_deep_orange_300 = new ColorRGBA("ff8a65");
      public static readonly ColorRGBA paper_deep_orange_400 = new ColorRGBA("ff7043");
      public static readonly ColorRGBA paper_deep_orange_500 = new ColorRGBA("ff5722");
      public static readonly ColorRGBA paper_deep_orange_600 = new ColorRGBA("f4511e");
      public static readonly ColorRGBA paper_deep_orange_700 = new ColorRGBA("e64a19");
      public static readonly ColorRGBA paper_deep_orange_800 = new ColorRGBA("d84315");
      public static readonly ColorRGBA paper_deep_orange_900 = new ColorRGBA("bf360c");
      public static readonly ColorRGBA paper_deep_orange_a100 = new ColorRGBA("ff9e80");
      public static readonly ColorRGBA paper_deep_orange_a200 = new ColorRGBA("ff6e40");
      public static readonly ColorRGBA paper_deep_orange_a400 = new ColorRGBA("ff3d00");
      public static readonly ColorRGBA paper_deep_orange_a700 = new ColorRGBA("dd2c00");

      public static readonly ColorRGBA paper_brown_50 = new ColorRGBA("efebe9");
      public static readonly ColorRGBA paper_brown_100 = new ColorRGBA("d7ccc8");
      public static readonly ColorRGBA paper_brown_200 = new ColorRGBA("bcaaa4");
      public static readonly ColorRGBA paper_brown_300 = new ColorRGBA("a1887f");
      public static readonly ColorRGBA paper_brown_400 = new ColorRGBA("8d6e63");
      public static readonly ColorRGBA paper_brown_500 = new ColorRGBA("795548");
      public static readonly ColorRGBA paper_brown_600 = new ColorRGBA("6d4c41");
      public static readonly ColorRGBA paper_brown_700 = new ColorRGBA("5d4037");
      public static readonly ColorRGBA paper_brown_800 = new ColorRGBA("4e342e");
      public static readonly ColorRGBA paper_brown_900 = new ColorRGBA("3e2723");

      public static readonly ColorRGBA paper_grey_50 = new ColorRGBA("fafafa");
      public static readonly ColorRGBA paper_grey_100 = new ColorRGBA("f5f5f5");
      public static readonly ColorRGBA paper_grey_200 = new ColorRGBA("eeeeee");
      public static readonly ColorRGBA paper_grey_300 = new ColorRGBA("e0e0e0");
      public static readonly ColorRGBA paper_grey_400 = new ColorRGBA("bdbdbd");
      public static readonly ColorRGBA paper_grey_500 = new ColorRGBA("9e9e9e");
      public static readonly ColorRGBA paper_grey_600 = new ColorRGBA("757575");
      public static readonly ColorRGBA paper_grey_700 = new ColorRGBA("616161");
      public static readonly ColorRGBA paper_grey_800 = new ColorRGBA("424242");
      public static readonly ColorRGBA paper_grey_900 = new ColorRGBA("212121");

      public static readonly ColorRGBA paper_blue_grey_50 = new ColorRGBA("eceff1");
      public static readonly ColorRGBA paper_blue_grey_100 = new ColorRGBA("cfd8dc");
      public static readonly ColorRGBA paper_blue_grey_200 = new ColorRGBA("b0bec5");
      public static readonly ColorRGBA paper_blue_grey_300 = new ColorRGBA("90a4ae");
      public static readonly ColorRGBA paper_blue_grey_400 = new ColorRGBA("78909c");
      public static readonly ColorRGBA paper_blue_grey_500 = new ColorRGBA("607d8b");
      public static readonly ColorRGBA paper_blue_grey_600 = new ColorRGBA("546e7a");
      public static readonly ColorRGBA paper_blue_grey_700 = new ColorRGBA("455a64");
      public static readonly ColorRGBA paper_blue_grey_800 = new ColorRGBA("37474f");
      public static readonly ColorRGBA paper_blue_grey_900 = new ColorRGBA("263238");
  }
}
